services:
  higgs-tts:
    build: .
    container_name: higgs-tts
    shm_size: "32g"
    ipc: host
    network_mode: host
    privileged: true
    volumes:
      - ${HOME}/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      /bin/zsh -c "
        hf download bosonai/higgs-audio-v3-tts-4b &&
        sgl-omni serve --model-path bosonai/higgs-audio-v3-tts-4b --port 8000
      "
